x-default-healthcheck: &default-healthcheck
  interval: 60s
  timeout: 20s
  retries: 5
  start_period: 120s
  start_interval: 20s
services:
  elasticsearch:
    ports: !reset []
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: -Xms2g -Xms2g
    healthcheck:
      test:     
        [ "CMD-SHELL", "curl -s --user elastic:${ELASTIC_PASSWORD} -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'" ]
      <<: *default-healthcheck
  logstash:
    ports: !reset []
    expose:
      - 5044
      - 50000/tcp
      - 50000/udp
      - 9600
    environment:
      LS_JAVA_OPTS: -Xms2g -Xms2g
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:9600"]
      <<: *default-healthcheck
  kibana:
    ports: !reset []
    expose:
      - 5601
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:5601/api/status"]
      <<: *default-healthcheck
